# Generated by Django 4.0.5 on 2022-06-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='No.')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='コード')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品名')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('description', models.TextField(blank=True, null=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='なにする？')),
            ],
        ),
    ]
