# Generated by Django 4.0.5 on 2022-06-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Hoge',
        ),
    ]
